### ISSUE TITLE
Sortable column definition property defaults to true instead of false

### ISSUE THREAD

**Issue by Blackbaud-ElainaCole** [blackbaud/skyux-ag-grid#91] opened 2020-12-03 19:44 UTC
**The expected behavior**: Column property `sortable` should default to false. See [ag-grid Column Properties documentation](https://www.ag-grid.com/javascript-grid-column-properties/). 

**The actual behavior**: It defaults to true.

**Steps to reproduce**: 
1. [Go to documentation for sky-ag-grid](https://developer.blackbaud.com/skyux/components/data-entry-grid)
2. Click on column headers in example to sort
3. Look at column definitions in data-entry-grid-demo.component.ts and see `sortable` is not specified

**Workaround**: There is a workaround where you can just set `sortable` on the column definition to false to get rid of the sorting indicators.

From: Consumer
Impact: Low
Severity: Low
Type: Bug

**Comment by Blackbaud-SteveBrush** [comment] 2020-12-04 16:03
Closing. This is expected behavior since the majority of use cases for grid columns is to enable sorting behavior.

See documentation for SKY UX Grid component `isSortable`, here: https://developer.blackbaud.com/skyux-grids/docs/grid#class-skygridcolumncomponent

**Closed by Blackbaud-SteveBrush** 2020-12-04 16:03 UTC
